### ISSUE TITLE
Multiple values for same filter

### ISSUE THREAD

**Issue by CostantiniMatteo** [beam-community/jsonapi#235]
The jsonapi spec states that multiple filter values can be combined in a comma-separated list. For example:

```
GET /comments?filter[post]=1,2 HTTP/1.1
```

However, I noticed that the library returns a string `"1,2"` instead of splitting it and returning `["1", "2"]`.

Is this by design, and therefore such cases needs to be handled manually by splitting the string?
I would be happy to implement it, if the change is welcome.

Thank you!

**Comment by jherdman** [comment]
Definitely a welcome change.
