### ISSUE TITLE
`options` parameter in serialize function is not supported by index et show function

### ISSUE THREAD

**Issue by lohayon** [beam-community/jsonapi#242]
In the documentation, it seems to be an options parameter that be handled in the paginator
![image](https://user-images.githubusercontent.com/11374758/99256156-a4dc5d80-281d-11eb-8f7b-153650f8aa75.png)

but the code does not handle it.
It is never sent to the serializer. 
Please, see :+1: https://github.com/jeregrine/jsonapi/blob/master/lib/jsonapi/view.ex#L261

**Comment by lucacorti** [comment]
It is sent to the serializer if you pass the `:options` key to `render("index.json", %{...})`.
