### ISSUE TITLE
Migrating to BEAM Community org

### ISSUE THREAD

**Issue by doomspork** [beam-community/jsonapi#251]
Howdy everyone 👋  I wanted to throw something out there since we've been having some trouble keeping up with PRs here: @jeregrine would you be open to migrating this repo to https://github.com/beam-community? I'm happy to invite yourself and all the other contributors to the org.

The goal of BEAM community is to build an organization able to support important Elixir packages when maintainers may be too overwhelmed and unable to continue to support things moving forward. Slowly but surely we've been picking up packages and maintainers.

Open to other ideas but I know many folks use this library and I'd love to see it continue to be supported 🎉 

cc @snewcomer @jherdman @mitchellhenke @lucacorti

**Comment by jeregrine** [comment]
Ehhh I'm not sure I how I feel about it, its not such an active project we need to prioritize moving it. If this is a very important issue to ya'll I'd reconsider it for sure. 


I worry the beam-community project is pretty new and that it too might lose steam, my gut says wait and see.

**Comment by doomspork** [comment]
Sounds good! 

Just for the record: The folks involved in @beam-community have been supporting projects across @elixir-lang for a number of years now individually. We organized under a common organization a few years ago now at which time I moved [elixir-companies.com](https://github.com/beam-community/elixir-companies) and [ua_parser](https://github.com/beam-community/ua_parser) there at least 2 years ago and that group has kept those projects up-to-date alongside [avro_ex](https://github.com/beam-community/avro_ex) which was moved over by the then maintainer due to their having so little time.

I'm fine with for keeping the project here. I do think would be great to see other maintainers getting more involved or add more maintainers such at @lucacorti 😁

**Comment by jeregrine** [comment]
Hows everyone else feel?

**Comment by lucacorti** [comment]
@doomspork @jeregrine I'll leave this to you guys and meanwhile see if I can help with getting PRs through, cutting new releases, etc.

**Comment by lucacorti** [comment]
@doomspork @jeregrine 

As I said, at dottori.it we are using the library quite extensively. I don't want to start any drama, and I am grateful for the work that you have done on the code, but we are starting to feel the need to move stuff forward faster. Currently, we depend on github or forked code because changes we depend on are still unreleased and it is unclear if and when this could happen. So we are basically running unreleased code.

Of course, this is open source, and we all work on this when we can and with the resources we have. What I want to say is that moving the project org is not really the issue here. Avoiding stalling development and moving the project forward is.

We actively use the library and are willing to help maintain it, review code, roll releases, etc. Also, I have ideas for further evolution, but those are more radical and need discussion and work. We are willing to put in work and ideas, otherwise at some point I think forking and maintaining our own version will be cheaper and inevitable but, honestly, I'd love not to.

Thanks for the code and the work you put into this. I hope we can move the project forward and make it gain traction.

**Comment by jeregrine** [comment]
@doomspork if you think changing the org will make it easier to manage for you than we should do it. 

@lucacorti I do appreciate effort in adding features and helping but this is a volunteer effort. It is not appropriate to pressure volunteers into meeting your deadlines and expectations. Nor is it alright to directly mention maintainers and asking for essentially free labour.

**Comment by lucacorti** [comment]
@jeregrine I think I tried as hard as possible to make it clear that it was not my intention to criticize or pressure the work that as been done and how it has been done. I am offering help and my offer stands. I have no deadlines, I am just expressing concerns, and I have been doing a little share of work.

My intention was not to criticize and or pressure anyone, but to find solutions. and I am sorry it you felt it was something else. All the best.

**Comment by doomspork** [comment]
@jeregrine the real advantage is having _a lot_ more maintainers to help move some of this stuff along. I'm still open to bringing this into the org but I don't want you to feel pressured. 

Now that I've figured out how to handle releases with GitHub Actions we can do that here or there now 🎉  See an example here: https://github.com/beam-community/scrivener_headers (I haven't yet got releases or tagging in there but this allows for easier release which was my goal)

**Comment by jeregrine** [comment]
You’ve done a ton of good work here and I don’t want to slow you down or get in your way. This repo is as much(if not more) yours than mine at this point :)

**Comment by jherdman** [comment]
Related, I think I ought to officially step down as a maintainer. I simply haven't the time or focus for this project, and there's no need for me to have access to all of the goodies.

**Comment by jeregrine** [comment]
@doomspork thanks for reminding me of this :P 

I totally forgot and let me be 100% clear, let me know what I have to do transfer it to the beam community and I'll do it.

**Comment by jherdman** [comment]
Along these lines, I think it's time for me to step away from this project. I haven't the time any more to keep up with it. Thank you all so much for allowing me to contribute to this project I such a meaningful way for so long. Best of luck!

**Comment by jeregrine** [comment]
@jherdman Done.

@doomspork please feel free to invite and or give me the place to transfer the repo to, and I'll get this done.

**Comment by doomspork** [comment]
@jeregrine you are invited 🎉
