### ISSUE TITLE
Add GitHub Actions workflow for Hex package releases

### ISSUE THREAD

**Issue by doomspork** [beam-community/jsonapi#261]
@yordis this repo would be another great candidate for the workflow you've put together. Would you be interested in taking care of this one?

**Comment by yordis** [comment]
@doomspork My pleasure to help on anything I can, absolutely.

**Comment by doomspork** [comment]
> Either add me to the org, or get ready for an MR, let share some directions on it.

I invited you moments after adding this issue 😁
