### ISSUE TITLE
Publish New Version on Hex

### ISSUE THREAD

**Issue by TylerPachal** [beam-community/jsonapi#274]
I was surprised to see that the latest version of this library to be published [on Hex is `1.3.0` from Mar 21, 2020](https://hex.pm/packages/jsonapi).  There have been quite a few commits since then, and according to the `mix.exs` file we are now on version `1.4.0`.  Could `1.4.0` be published to Hex?

Thanks!

**Comment by doomspork** [comment]
We will get a new version released here shortly @TylerPachal! I'm going to work with @btkostner to setup workflows to ensure we keep the latest and greatest on Hex.

**Comment by yordis** [comment]
More than happy to help with the CI situation if you want me to

**Comment by TylerPachal** [comment]
@doomspork I am closing this now, since version 1.4.0 is now available on Hex 🥳
