### ISSUE TITLE
Allow conditionally hidden fields

### ISSUE THREAD

**Issue by protestContest** [beam-community/jsonapi#313]
The `hidden/0` view callback is handy to remove sensitive fields in views. In some cases, an API may want to hide certain fields by default, but show them in some cases (in my application's case, some fields should be visible if specifically requested as part of a [sparse fieldset](https://jsonapi.org/format/#fetching-sparse-fieldsets)).

It would be handy if the `hidden` callback accepted `conn` as an argument, so the application could decide what fields to hide for a particular request.

Any thoughts on this? I'm happy to open a PR for the change.

Related issue: #68

**Comment by mattpolzin** [comment]
that sounds like a reasonable solution as long as you don't need to omit any relationships (really, anything outside of `attributes`) conditionally. just cuz the `hidden/0` function only operates on fields to begin with.
