### ISSUE TITLE
Assertion for tests

### ISSUE THREAD

**Issue by ravecat** [beam-community/jsonapi#319]
How can you test API responses that conform to the JSON API specification? Do you have any assertions for tests?

**Comment by mattpolzin** [comment]
We try to cover this library's correctness (that responses are valid JSON:API) in the test suite in this project, but assuming you're asking about validating the specifics of the data from your own APIs, there are not currently any assertion helpers. Fortunately, I've personally found JSON:API's data structures to be light-weight enough that using Elixir's pattern matching assertion pattern on the entire response body is pretty manageable. For example, https://github.com/beam-community/jsonapi/blob/main/test/jsonapi_test.exs#L342..L352.
