### ISSUE TITLE
JSONAPI.ContentTypeNegotiation ignore some methods for validation

### ISSUE THREAD

**Issue by ravecat** [beam-community/jsonapi#320]
Thank you for your work, I am integrating your lib into my application and I have a question.

Seen [source code](https://github.com/beam-community/jsonapi/blob/main/lib/jsonapi/plugs/content_type_negotiation.ex#L22) of `JSONAPI.ContentTypeNegotiation` for validation and I'm surprised that he's ignoring some of the methods

```elixir
  def call(%{method: method} = conn, _opts) when method in ["DELETE", "GET", "HEAD"], do: conn

  def call(conn, _opts) do
    conn
    |> content_type
    |> accepts
    |> respond
  end
```

because [spec](https://jsonapi.org/format/#jsonapi-media-type) requires that communication between the client and servers should be done with the `application/vnd.api+json` header.

Could you clarify that point

**Comment by mattpolzin** [comment]
The referenced plug specifically checks that the Content-Type request header is valid. Since that header specifies the type of the request body, it is not relevant for HEAD, GET, or DELETE requests. One could theoretically be a stickler and deny a request that has no body but still specifies a Contnet-Type (of any value), but that’s probably rarely done in practice.

**Comment by mattpolzin** [comment]
On second thought, since the plug does bother to validate the accept header as well, it does look like a bug that it ignores some http verbs. Would be better if it validated content-type and accept for put/post/patch and still validated accept for the rest.

**Comment by ravecat** [comment]
@mattpolzin thank you for you answer

update MIME configuration accroding [docs](https://hexdocs.pm/mime/MIME.html)

```elixir
config :mime, :types, %{
  "application/vnd.api+json" => ["json-api"]
}
```

and my pipeline

```elixir
  pipeline :api do
    plug :accepts, ["json-api"]
    plug JSONAPI.EnsureSpec
    plug JSONAPI.Deserializer
    plug JSONAPI.UnderscoreParameters
  end
```

**Comment by mattpolzin** [comment]
Looking good!
